### PR TITLE
Add global

### PR DESCRIPTION
**Pull request by mantoni**
This will be used by lolex, nise and sinon to detect the correct global object in node, browsers and web workers.

### CODE REVIEW

**Comment by SimenB** [comment]
This should also check for `globalThis` since that's the actual specced out global object which works on both node and the browser (and esm).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

**Comment by mantoni** [comment]
@SimenB Would you make that the very first check and use the current implementation as a fallback?

**Comment by mroderick** [comment]
`globalThis` is in the draft spec and not well supported yet.

2019-12-19 at 13 25

I would suggest keeping the current implementation as fallback. We don't need to worry about file size, more about not attracting bug reports :)

**Comment by mantoni** [comment]
@mroderick I agree. I wasn't thinking of removing the current detection. I'm just wondering in which order we should do the checks.

**Comment by mroderick** [comment]
I see (I am still affected by the flu)

**Comment by SimenB** [comment]
>@SimenB Would you make that the very first check and use the current implementation as a fallback?

Yeah, that makes sense to me 👍 

>`globalThis` is in the draft spec and not well supported yet.

Draft spec? It's been stage 4 since October (https://github.com/tc39/proposals/commit/3336d8461b54215b70356de861d2836bc91fd8ef) and part of the standard. Either way, I didn't mean there should _only_ be a check for `globalThis`, just that it should be there.

---

You might consider just using https://github.com/es-shims/globalThis, but I think the current approach (plus checking for `globalThis`) is fine 👍

**Comment by mroderick** [comment]
> Draft spec? It's been stage 4 since October ([tc39/proposals@3336d84](https://github.com/tc39/proposals/commit/3336d8461b54215b70356de861d2836bc91fd8ef)) and part of the standard.

From the page you linked to:

2019-12-19 at 14 01

Is that page incorrect? If so, how do we fix it?

**Comment by SimenB** [comment]
Ah. That's just because the current version of the spec (es2020) hasn't been published/finalized yet.

**Pull request merged**
